import type { Localized } from "../../lib/i18n";

export const S = {
  capacityTitle: { en: "Pool capacity", zh: "显存池容量" },
  capacitySub: { en: "Teaching model · 24 units · state: 2 units/request · no prefix sharing", zh: "示意模型 · 总量 24 单位 · 状态占 2 单位/请求 · 不含前缀共享" },
  requests: { en: "Requests", zh: "请求数量" },
  kvSize: { en: "KV units per request", zh: "每个请求的 KV 用量" },
  short: { en: "Short requests", zh: "短请求" },
  long: { en: "Long contexts", zh: "长上下文" },
  balanced: { en: "Balanced", zh: "均衡负载" },
  full: { en: "Capacity limit", zh: "容量上限" },
  static: { en: "Static pools", zh: "固定分池" },
  unified: { en: "Unified pool", zh: "共享池" },
  admitted: { en: "Admitted", zh: "已接纳" },
  waiting: { en: "Waiting", zh: "等待" },
  free: { en: "Free units", zh: "空闲单位" },
  state: { en: "Recurrent state", zh: "循环状态" },
  kv: { en: "Full-attention KV", zh: "全注意力 KV" },
  gap: { en: "Shared free region", zh: "共享空闲区" },
  unused: { en: "Free", zh: "空闲" },
  fixedWall: { en: "Fixed boundary", zh: "固定边界" },
  address: { en: "Physical offset", zh: "物理偏移" },
  units: { en: "units", zh: "单位" },
  request: { en: "Request", zh: "请求" },
  compactionTitle: { en: "Page compaction", zh: "页面压实" },
  compactionSub: { en: "Normalized sizes · state block: 4 units · KV page: 1 unit", zh: "归一化尺寸 · 状态块 4 单位 · KV 页 1 单位" },
  initial: { en: "Allocated", zh: "分配完成" },
  release: { en: "Release B", zh: "释放 B" },
  compact: { en: "Move C", zh: "搬移 C" },
  grow: { en: "Add KV", zh: "分配 KV" },
  virtualIds: { en: "Request → page ID", zh: "请求 → 虚拟页号" },
  mapping: { en: "Page ID → physical offset", zh: "虚拟页号 → 物理偏移" },
  hole: { en: "Interior hole", zh: "内部空洞" },
  sharedGap: { en: "Shared gap", zh: "共享空闲区" },
  moved: { en: "C: 8 → 4", zh: "C：8 → 4" },
  moveAlt: { en: "State C moves from offset 8 to 4. Its virtual ID stays C.", zh: "状态 C 从偏移 8 搬到 4，虚拟编号仍为 C。" },
  benchTitle: { en: "Cache eviction", zh: "缓存驱逐" },
  benchSub: { en: "Qwen3.5-4B · RTX 5090 32 GB · Triton · unified memory in both arms", zh: "Qwen3.5-4B · RTX 5090 32 GB · Triton · 两组均启用 Unified Memory" },
  before: { en: "Before #33091", zh: "#33091 前" },
  after: { en: "After #33091", zh: "#33091 后" },
  retained: { en: "Retained prefixes", zh: "保留的前缀" },
  replay: { en: "Total replay E2E", zh: "重放总耗时" },
  prefill: { en: "Mean replay prefill", zh: "重放平均 prefill" },
  retentionDelta: { en: "1.9× retained prefixes", zh: "前缀保留量 1.9 倍" },
  replayDelta: { en: "37.9% less time", zh: "耗时降低 37.9%" },
  prefillDelta: { en: "43.6% less time", zh: "耗时降低 43.6%" },
  retainedLegend: { en: "Retained", zh: "保留" },
  evictedLegend: { en: "Evicted", zh: "已驱逐" },
  benchNote: { en: "28 prefixes × ~390 tokens → 7,000-token pressure request → 28 replays · timing: median of 6 runs", zh: "28 段前缀 × 约 390 tokens → 7,000-token 压力请求 → 28 次重放 · 耗时：6 次运行中位数" },
  source: { en: "Source: sglang#33091", zh: "来源：sglang#33091" },
  historyTitle: { en: "Implementation history", zh: "实现与发布" },
  historySub: { en: "2026 · UTC dates · checked September 9", zh: "2026 年 · UTC 日期 · 9 月 9 日核实" },
  pr: { en: "Merged PR", zh: "PR 合入" },
  blog: { en: "Official blog", zh: "官方博客" },
  releaseType: { en: "Release", zh: "版本发布" },
  historyLinks: { en: "Source records", zh: "原始记录" },
  pipeline: { en: "Static pools → shared bytes → shared-capacity eviction", zh: "固定分池 → 共享字节 → 按共享容量停止驱逐" },
} satisfies Record<string, Localized>;

export const HISTORY = [
  {
    date: "2026-07-01", type: "pr", label: "#29678",
    title: { en: "Initial shared pool", zh: "共享池初版" },
    detail: { en: "Hybrid Mamba/GDN and SWA support. Two sub-pools grow from opposite ends and keep page IDs stable during compaction.", zh: "支持混合 Mamba/GDN 与 SWA。两个子池从两端增长，压实后保留虚拟页号。" },
    links: [{ label: "#29678", url: "https://github.com/sgl-project/sglang/pull/29678" }, { label: "4a8e768", url: "https://github.com/sgl-project/sglang/commit/4a8e76805c27d8fffed4b8759593310a6ebde298" }],
  },
  {
    date: "2026-07-27", type: "blog", label: "LMSYS",
    title: { en: "Kimi K3 design write-up", zh: "Kimi K3 设计介绍" },
    detail: { en: "The Kimi K3 launch blog explains the shared pool for KV and recurrent state and announces a later implementation deep dive.", zh: "Kimi K3 发布博客介绍 KV 与循环状态为什么需要共享池，并预告后续实现详解。" },
    links: [{ label: "LMSYS Blog", url: "https://www.lmsys.org/blog/2026-07-27-kimi-k3-day0-support#unified-memory-one-pool-for-both-kinds-of-state" }],
  },
  {
    date: "2026-08-08", type: "releaseType", label: "v0.5.17",
    title: { en: "MLA hybrid support", zh: "支持 MLA 混合模型" },
    detail: { en: "Kimi-Linear gains Triton MLA-hybrid-Mamba support and paged MLA backend integration.", zh: "Kimi-Linear 增加 Triton MLA-hybrid-Mamba 支持及分页 MLA 后端接入。" },
    links: [{ label: "v0.5.17", url: "https://github.com/sgl-project/sglang/releases/tag/v0.5.17" }, { label: "#32971", url: "https://github.com/sgl-project/sglang/pull/32971" }],
  },
  {
    date: "2026-08-22", type: "releaseType", label: "v0.5.18",
    title: { en: "DSpark and PD integration", zh: "接入 DSpark 与 PD 分离" },
    detail: { en: "DSpark integration and PD disaggregation for the Kimi-Linear MLA-hybrid path.", zh: "接入 DSpark，并支持 Kimi-Linear MLA 混合路径的 PD 分离。" },
    links: [{ label: "v0.5.18", url: "https://github.com/sgl-project/sglang/releases/tag/v0.5.18" }, { label: "#33974", url: "https://github.com/sgl-project/sglang/pull/33974" }, { label: "#33362", url: "https://github.com/sgl-project/sglang/pull/33362" }],
  },
  {
    date: "2026-08-26", type: "pr", label: "#33091",
    title: { en: "Shared-capacity eviction", zh: "按共享容量停止驱逐" },
    detail: { en: "Allocation-triggered eviction stops when the shared allocator can fulfill the request, including capacity released by another sub-pool.", zh: "分配触发的驱逐在共享分配器能够满足请求时停止，并计入其他子池释放出的容量。" },
    links: [{ label: "#33091", url: "https://github.com/sgl-project/sglang/pull/33091" }],
  },
  {
    date: "2026-09-05", type: "releaseType", label: "v0.5.19",
    title: { en: "Three sub-pools and more backends", zh: "三个子池与更多后端" },
    detail: { en: "Full KV, SWA KV and recurrent state can share one buffer. This release also includes more attention backends and the eviction improvement above.", zh: "Full KV、SWA KV 与循环状态可共用一个缓冲区。该版本还包含更多注意力后端与上面的驱逐优化。" },
    links: [{ label: "v0.5.19", url: "https://github.com/sgl-project/sglang/releases/tag/v0.5.19" }, { label: "#35177", url: "https://github.com/sgl-project/sglang/pull/35177" }, { label: "#34613", url: "https://github.com/sgl-project/sglang/pull/34613" }],
  },
] as const;
