import type { Localized } from "../../lib/i18n";

export const LOCATION = {
  title: { en: "Where the cache lives", zh: "缓存存在哪里" },
  note: { en: "Example deployment: two serving nodes connected to a shared storage service.", zh: "部署示例：两个推理节点接入同一个共享存储服务。" },
  path: { en: "Storage path: ", zh: "存储路径：" },
  cluster: { en: "Cluster", zh: "集群" },
  node: { en: "Serving node", zh: "推理节点" },
  open: { en: "Explore", zh: "点开查看" },
  back: { en: "Back", zh: "返回上层" },
  host: { en: "CPU DRAM · L2", zh: "CPU DRAM · L2" },
  storage: { en: "External storage · L3", zh: "外部存储 · L3" },
  network: { en: "Cluster network", zh: "集群网络" },
  server: { en: "Inside one server", zh: "一台服务器内部" },
  package: { en: "GPU package", zh: "GPU 封装" },
  compute: { en: "GPU compute die", zh: "GPU 计算芯片" },
  attention: { en: "Attention", zh: "Attention 计算" },
  hbm: { en: "HBM stacks", zh: "HBM 显存堆栈" },
  l1: { en: "L1 KV pool", zh: "L1 KV 池" },
  dram: { en: "Host DRAM", zh: "主机 DRAM" },
  l2: { en: "Instance-private L2 pool", zh: "实例私有 L2 池" },
  other: { en: "Other host memory", zh: "其余主机内存" },
  cpu: { en: "CPU", zh: "CPU" },
  memoryBus: { en: "Memory channels", zh: "内存通道" },
  remote: { en: "Remote memory", zh: "远端内存" },
  disks: { en: "Distributed storage", zh: "分布式存储" },
  localFile: { en: "Local file backend", zh: "本地文件后端" },
  localDisk: { en: "Disk in the serving node", zh: "推理节点内的磁盘" },
  alternatives: { en: "L3 backend alternatives", zh: "L3 后端的不同选择" },
  shared: { en: "Shared storage service", zh: "共享存储服务" },
  clusterDetail: { en: "L1 and L2 belong to serving instances. In this deployment, both nodes connect to the same L3 service over the network.", zh: "L1、L2 属于各自的服务实例。这个部署中，两个节点通过网络接入同一个 L3 服务。" },
  gpuDetail: { en: "Each GPU has its own HBM, packaged alongside its compute die. The L1 KV pool occupies part of that HBM; weights and other buffers also use GPU memory.", zh: "每块 GPU 都有自己的 HBM，与计算芯片一起封装。L1 KV 池占用其中一部分；模型权重和其他 buffer 也会使用显存。" },
  hostDetail: { en: "CPU DRAM is the server’s system memory, outside the GPU package. HiCache allocates its L2 pool here. This pool is private to the serving instance, even when multiple instances run on one server.", zh: "CPU DRAM 是服务器的系统内存，位于 GPU 封装之外。HiCache 在这里分配 L2 池。即使多个实例运行在同一台服务器上，它们的 L2 池也各自私有。" },
  storageDetail: { en: "L3 is accessed through a storage backend. A shared service can run inside the same cluster and serve compatible instances. L3 can also use local files, so “external” does not mean outside the cluster or necessarily shared.", zh: "L3 通过存储后端访问。共享服务可以部署在同一个集群内，供配置兼容的实例复用缓存。L3 也可以使用本地文件，因此“外部”不代表在集群之外，也不代表一定共享。" },
  route: { en: "L3 hit: storage → host DRAM → GPU HBM → attention", zh: "L3 命中：存储 → 主机 DRAM → GPU HBM → Attention" },
} satisfies Record<string, Localized>;

export const TEXT = {
  request: { en: "Request prefix", zh: "请求前缀" },
  root: { en: "Root", zh: "根节点" },
  gpu: { en: "GPU HBM", zh: "GPU HBM" },
  host: { en: "CPU DRAM", zh: "CPU DRAM" },
  storage: { en: "External storage", zh: "外部存储" },
  query: { en: "Storage key", zh: "存储查询键" },
  local: { en: "Local prefix match", zh: "本地前缀匹配" },
  lookup: { en: "Storage lookup", zh: "查询外部存储" },
  prefetch: { en: "Storage → CPU", zh: "存储 → CPU" },
  load: { en: "CPU → GPU", zh: "CPU → GPU" },
  ready: { en: "KV ready on GPU", zh: "GPU KV 就绪" },
  absent: { en: "No local node", zh: "无本地节点" },
  layer: { en: "Layer", zh: "层" },
  overlapTitle: { en: "Overlapping data transfers and computation", zh: "重叠搬运与计算操作" },
  overlapNote: { en: "Illustrative units: page read 1 · layer load 1 · layer compute 2", zh: "示意时间：整页读取 1 · 逐层搬运 1 · 每层计算 2" },
  storageRead: { en: "L3 → Host", zh: "L3 → Host" },
  wholePage: { en: "whole page", zh: "整页" },
  pageLabel: { en: "Page", zh: "页" },
  threePages: { en: "3 pages", zh: "3 页" },
  hostReady: { en: "3 pages in Host", zh: "Host 三页到齐" },
  serial: { en: "Load all layers first", zh: "先加载全部层" },
  overlap: { en: "Overlap with compute", zh: "与计算重叠" },
  transfer: { en: "Host → GPU", zh: "Host → GPU" },
  compute: { en: "GPU compute", zh: "GPU 计算" },
  elapsed: { en: "Completion", zh: "完成时刻" },
  unit: { en: "units", zh: "单位" },
  benchTitle: { en: "Long-context benchmark", zh: "长上下文基准" },
  benchNote: { en: "DeepSeek-R1 · 8 × H20-3e · LooGLE", zh: "DeepSeek-R1 · 8 × H20-3e · LooGLE" },
  ttft: { en: "Average TTFT (s) ↓", zh: "平均 TTFT（秒）↓" },
  throughput: { en: "Input throughput (tokens/s) ↑", zh: "输入吞吐（tokens/s）↑" },
  gpuOnly: { en: "GPU only", zh: "仅 GPU" },
  l2: { en: "+ CPU L2", zh: "+ CPU L2" },
  l3: { en: "+ 3FS L3", zh: "+ 3FS L3" },
  populated: { en: "+ Prepopulated L3", zh: "+ 预先填充 L3" },
  warmNote: { en: "Prepopulated L3: reusable KV is written to storage before the benchmark starts.", zh: "预先填充 L3：基准开始前，先把可复用的 KV 写入存储。" },
  relative: { en: "Relative to GPU only", zh: "相对仅 GPU" },
  lower: { en: "lower TTFT", zh: "TTFT 降低" },
  higher: { en: "throughput", zh: "吞吐" },
} satisfies Record<string, Localized>;

export const PREFETCH = {
  title: { en: "Prefetch policies", zh: "预取策略" },
  total: { en: "Reusable prefix", zh: "可复用前缀" },
  ready: { en: "Ready at B’s turn", zh: "轮到 B 时已就绪" },
  budget: { en: "Extra wait limit", zh: "额外等待上限" },
  zero: { en: "t = 0: B’s turn · time in illustrative units", zh: "t = 0：轮到 B · 时间为示意单位" },
  "best-effort": { en: "Best-effort", zh: "Best-effort" },
  "wait-complete": { en: "wait-complete", zh: "wait-complete" },
  timeout: { en: "timeout", zh: "timeout" },
  initial: { en: "Already ready", zh: "原已就绪" },
  fetched: { en: "Fetched while waiting", zh: "等待中读回" },
  missing: { en: "Recompute", zh: "需要重算" },
  reuse: { en: "Reuse", zh: "复用" },
  recompute: { en: "Recompute", zh: "重算" },
  wait: { en: "Wait for L3", zh: "等待读取" },
  load: { en: "Host → GPU", zh: "Host → GPU" },
  question: { en: "New question", zh: "新问题计算" },
  start: { en: "B starts", zh: "B 开始执行" },
  finish: { en: "First token", zh: "首 token" },
  fastest: { en: "Fastest", zh: "最快" },
  slowest: { en: "Slowest", zh: "最慢" },
  tied: { en: "Tie", zh: "持平" },
  cost: { en: "Time to recompute the missing X − Y tokens", zh: "重算缺失的 X − Y 个 token 所需时间" },
  cheap: { en: "Cheap to recompute", zh: "重算便宜" },
  expensive: { en: "Expensive to recompute", zh: "重算昂贵" },
  unit: { en: "units", zh: "单位" },
  assumption: {
    en: "Illustrative model: L3 reads 2 tokens/unit; recompute time scales with missing tokens. Each policy includes 1 unit for Host → GPU and 1 for the new question.",
    zh: "示意模型：L3 每单位读回 2 个 token，重算耗时与缺失 token 数成正比。三种策略均计入 Host → GPU 搬运 1 单位、新问题计算 1 单位。",
  },
} satisfies Record<string, Localized>;

export const LAYOUT = {
  title: { en: "KV layout and transfer", zh: "KV 布局与搬运" },
  before: { en: "Before: Host by layer", zh: "Before：Host 按模型层排列" },
  after: { en: "After: Host by page", zh: "After：Host 按页排列" },
  gpu: { en: "GPU \u00b7 L1", zh: "GPU · L1" },
  host: { en: "Host \u00b7 L2", zh: "Host · L2" },
  address: { en: "Memory order", zh: "内存排列" },
  layerGroup: { en: "Model layer", zh: "模型层" },
  pageGroup: { en: "Page", zh: "页" },
  page: { en: "Page", zh: "页" },
  layer: { en: "Layer", zh: "模型层" },
  diagram: { en: "Linear KV memory layout and transfers across GPU, Host and storage", zh: "GPU、Host 与存储之间的 KV 内存排列和搬运" },
  direction: { en: "Transfer direction", zh: "搬运方向" },
  backup: { en: "Backup: GPU \u2192 Host \u2192 L3", zh: "备份：GPU → Host → L3" },
  restore: { en: "Restore: L3 \u2192 Host \u2192 GPU", zh: "恢复：L3 → Host → GPU" },
  regions: { en: "Host memory regions", zh: "处 Host 内存区域" },
  wholeIO: { en: "Read or write one contiguous page", zh: "整块读写" },
  scatterIO: { en: "Gather or scatter the separated pieces", zh: "读写分散的数据段" },
  storage: { en: "External storage", zh: "外部存储" },
  play: { en: "Play", zh: "播放" },
  pause: { en: "Pause", zh: "暂停" },
  replay: { en: "Replay", zh: "重播" },
  reset: { en: "Reset", zh: "回到起点" },
  nextStep: { en: "Next transfer", zh: "下一步搬运" },
  ioProgress: { en: "Transfer progress", zh: "搬运进度" },
  ioBasis: { en: "Visual transfer steps; backend requests may be batched.", zh: "按演示搬运步骤计数；后端可批量提交请求。" },
  comparison: { en: "Before / After layout", zh: "Before / After 布局切换" },
  readingPiece: { en: "L3 → Host: read page fragment", zh: "L3 → Host：分段读取，页" },
  pages: { en: "pages", zh: "页" },
  done: { en: "Transfer complete", zh: "搬运完成" },
  backingUp: { en: "GPU \u2192 Host: batch copy across pages and model layers", zh: "GPU → Host：批量搬运多个页、多个模型层" },
  writingPage: { en: "Host \u2192 L3: save page", zh: "Host → L3：保存页" },
  readingPage: { en: "L3 \u2192 Host: read whole page", zh: "L3 → Host：整页读取，页" },
  restoringLayer: { en: "Host \u2192 GPU: restore model layer", zh: "Host → GPU：恢复模型层" },
} satisfies Record<string, Localized>;

export const REUSE = {
  title: { en: "How HiCache reuses a prefix", zh: "HiCache 怎样复用前缀" },
  request: { en: "New request", zh: "新请求" },
  document: { en: "Same document", zh: "同一份文档" },
  question: { en: "New question", zh: "新问题" },
  reuse: { en: "Reuse cached KV", zh: "复用缓存" },
  compute: { en: "Compute", zh: "需要计算" },
  l1Hit: { en: "L1 hit", zh: "L1 命中" },
  l2Hit: { en: "L2 hit", zh: "L2 命中" },
  l3Hit: { en: "L3 hit", zh: "L3 命中" },
  miss: { en: "No cache hit", zh: "全部未命中" },
  initial: { en: "Cache when the request arrives", zh: "请求到来时的缓存" },
  L1: { en: "GPU memory", zh: "GPU 显存" },
  L2: { en: "CPU memory", zh: "CPU 内存" },
  L3: { en: "External storage", zh: "外部存储" },
  present: { en: "Document KV cached", zh: "有文档缓存" },
  absent: { en: "No document cache", zh: "无文档缓存" },
  action: { en: "Next", zh: "接下来" },
  direct: { en: "L1 → reuse on GPU", zh: "L1 → GPU 直接复用" },
  fromL2: { en: "L2 → L1 → reuse on GPU", zh: "L2 → L1 → GPU 复用" },
  fromL3: { en: "L3 → L2 → L1 → reuse on GPU", zh: "L3 → L2 → L1 → GPU 复用" },
  cold: { en: "GPU computes the document + question", zh: "GPU 计算文档 + 新问题" },
  backup: { en: "Backup: L1 → L2 → L3", zh: "备份：L1 → L2 → L3" },
  backupNote: { en: "With backups enabled, lower tiers can retain a copy after GPU eviction.", zh: "启用备份后，GPU 清掉的缓存仍可能保留在下层。" },
} satisfies Record<string, Localized>;

export const REUSE_EXPLANATION = {
  l1Hit: { en: "The document’s KV is already on the GPU. Reuse it directly and compute only the new question.", zh: "文档的 KV 已在 GPU 上，直接复用，只计算新问题。" },
  l2Hit: { en: "The GPU copy is gone, but CPU memory still has it. Load it into L1, then compute only the new question.", zh: "GPU 上的副本已被清掉，但 CPU 内存里还有。搬回 L1 后，只计算新问题。" },
  l3Hit: { en: "Neither L1 nor L2 has the document’s KV, but L3 does. Fetch it into L2, load it into L1, and compute only the new question.", zh: "L1、L2 都没有文档缓存，但 L3 还有。先取到 L2，再搬到 L1，只计算新问题。" },
  miss: { en: "The document’s KV is missing from all three tiers. The GPU must compute both the document and the new question.", zh: "三层都找不到文档缓存。GPU 需要计算整份文档和新问题。" },
} satisfies Record<string, Localized>;

export const UPDATE = {
  timeline: { en: "HiCache design milestones", zh: "HiCache 技术演化时间线" },
  timelineNote: { en: "Design milestones · UTC merge dates", zh: "技术里程碑 · 合入 main 的 UTC 日期" },
  stateTitle: { en: "Backing up new recurrent snapshots", zh: "补存新生成的递归快照" },
  stateNote: { en: "Full attention + recurrent layers · write-through", zh: "全注意力层 + 递归层 · write-through" },
  baseline: { en: "Before", zh: "改动前" },
  fixed: { en: "After", zh: "改动后" },
  savedPrefix: { en: "A backed up", zh: "甲已备份" },
  branch: { en: "B creates snapshot", zh: "乙生成快照" },
  incremental: { en: "Back up snapshot", zh: "补存快照" },
  eviction: { en: "Evict GPU cache", zh: "GPU 驱逐" },
  recovery: { en: "Reuse document", zh: "再次复用文档" },
  full: { en: "Full-attention KV pool", zh: "全注意力 KV 池" },
  state0: { en: "After document + question A", zh: "读完「文档＋问题甲」" },
  state1: { en: "After document only", zh: "只读完「文档」" },
  newCopy: { en: "GPU → Host: copy the document snapshot only", zh: "GPU → Host：只补存文档快照" },
  noCopy: { en: "Full KV marked backed up → new snapshot skipped", zh: "全注意力 KV 已备份 → 新快照未触发补存" },
  draftTitle: { en: "DSpark L3 replay", zh: "DSpark L3 恢复" },
  draftNote: { en: "#30393 · DeepSeek-V4-Flash-0731 · 200 ShareGPT prompts · 128 output tokens/request", zh: "#30393 · DeepSeek-V4-Flash-0731 · 200 条 ShareGPT prompt · 每请求输出 128 token" },
  target: { en: "Target cache", zh: "Target 缓存" },
  draft: { en: "Draft cache", zh: "Draft 缓存" },
  restored: { en: "Restored", zh: "已恢复" },
  incomplete: { en: "Missing or mismapped", zh: "缺失或索引不匹配" },
  cold: { en: "Cold run", zh: "冷运行" },
  replay: { en: "L3 replay", zh: "L3 恢复运行" },
  acceptance: { en: "DSpark acceptance rate (%)", zh: "DSpark 接受率（%）" },
  acceptLength: { en: "Average accepted length", zh: "平均接受长度" },
  hostTitle: { en: "Host cache and transfer buffer", zh: "Host 缓存与传输缓冲" },
  hostNote: { en: "Two instances with compatible model configurations · shared prefix P", zh: "两个模型配置兼容的实例 · 共享前缀 P" },
  cacheMode: { en: "Host cache", zh: "Host 缓存" },
  bufferMode: { en: "Host buffer-only", zh: "Host 仅作缓冲" },
  instanceA: { en: "Instance A", zh: "实例 A" },
  instanceB: { en: "Instance B", zh: "实例 B" },
  privateHost: { en: "Private CPU memory", zh: "私有 CPU 内存" },
  sharedStorage: { en: "Shared L3 storage", zh: "共享 L3 存储" },
  freeSlot: { en: "Free slot", zh: "空闲槽" },
  retained: { en: "Retained copy P", zh: "保留副本 P" },
  staging: { en: "Staging P", zh: "中转 P" },
  produced: { en: "A: KV ready", zh: "A：KV 就绪" },
  backup: { en: "A: GPU → CPU", zh: "A：GPU → CPU" },
  stored: { en: "L3 backup complete", zh: "L3 备份完成" },
  fetched: { en: "B: L3 → CPU", zh: "B：L3 → CPU" },
  loaded: { en: "B: GPU ready", zh: "B：GPU 就绪" },
  statePool: { en: "Recurrent-state pool", zh: "递归状态池" },
  stateDocument: { en: "Document", zh: "文档" },
  stateQuestionA: { en: "Question A", zh: "问题甲" },
  stateQuestionB: { en: "Question B", zh: "问题乙" },
  stateRequestA: { en: "Request A", zh: "请求甲" },
  stateRequestB: { en: "Request B", zh: "请求乙" },
  stateBoundary: { en: "Shared prefix ends here", zh: "共享前缀到这里结束" },
  stateCached: { en: "Stored", zh: "已保存" },
  stateAbsent: { en: "Not stored", zh: "未保存" },
  stateNew: { en: "New snapshot", zh: "新生成" },
  stateEmpty: { en: "No document cache", zh: "没有文档缓存" },
  stateRestore: { en: "Host → GPU: document KV + document snapshot", zh: "Host → GPU：文档 KV ＋ 文档快照" },
  stateRecompute: { en: "Document snapshot missing → recomputation required", zh: "缺少文档快照 → 需要重算" },
  stateInitial: { en: "Host retains A’s KV and end snapshot", zh: "Host 已保存甲的 KV 和末尾快照" },
  stateCreated: { en: "While processing B: save the state at the document’s end", zh: "处理乙时：在文档末尾留下状态快照" },
  stateEvicted: { en: "The document’s GPU KV and snapshot are evicted", zh: "文档的 GPU KV 和快照已驱逐" },
  stateSlot: { en: "Separate snapshot", zh: "独立快照" },
} satisfies Record<string, Localized>;

// PR metadata verified through gh api; dates are UTC merges into main.
export const HISTORY = [
  {
    "pr": 2693,
    "date": "2025-02-24",
    "title": "Hierarchical Caching for SGLang",
    "url": "https://github.com/sgl-project/sglang/pull/2693",
    "label": {
      "en": "GPU and CPU cache tiers",
      "zh": "GPU 与 CPU 分层缓存"
    }
  },
  {
    "pr": 7313,
    "date": "2025-07-07",
    "title": "Kernels for efficient KV cache IO",
    "url": "https://github.com/sgl-project/sglang/pull/7313",
    "label": {
      "en": "Efficient CPU–GPU transfers",
      "zh": "高效 CPU–GPU 搬运"
    }
  },
  {
    "pr": 7704,
    "date": "2025-07-18",
    "title": "Hicache Storage Layer Prototype",
    "url": "https://github.com/sgl-project/sglang/pull/7704",
    "label": {
      "en": "External storage tier",
      "zh": "外部存储层"
    }
  },
  {
    "pr": 21259,
    "date": "2026-04-14",
    "title": "[HiCache & HybridModel] mooncake backend support DSA & mamba  model",
    "url": "https://github.com/sgl-project/sglang/pull/21259",
    "label": {
      "en": "Recurrent and auxiliary state storage",
      "zh": "递归状态与辅助 buffer 存储"
    }
  },
  {
    "pr": 30393,
    "date": "2026-08-06",
    "title": "[HiCache] Support packed and sidecar draft caches for MTP/EAGLE/DSpark",
    "url": "https://github.com/sgl-project/sglang/pull/30393",
    "label": {
      "en": "Target and draft state recovery",
      "zh": "Target 与 draft 状态恢复"
    }
  },
  {
    "pr": 33639,
    "date": "2026-08-10",
    "title": "[Hicache][2/2]Support Mamba branching in Unified Radix Cache with HiCache",
    "url": "https://github.com/sgl-project/sglang/pull/33639",
    "label": {
      "en": "Incremental branch-checkpoint backup",
      "zh": "分支 checkpoint 增量备份"
    }
  },
  {
    "pr": 34798,
    "date": "2026-08-19",
    "title": "[HiCache] Buffer-only mode for HiCache host memory layer",
    "url": "https://github.com/sgl-project/sglang/pull/34798",
    "label": {
      "en": "Host memory as a transfer buffer",
      "zh": "Host 内存改作传输缓冲"
    }
  }
] as const;
