import type { Localized } from "../../lib/i18n";

export const TEXT = {
  treeTitle: { en: "HiRadixTree and KV pools", zh: "HiRadixTree 与 KV 池" },
  treeNote: { en: "Schematic token segments and pool indices; all transfers succeed.", zh: "token 段与池索引均为示意；假设传输成功。" },
  request: { en: "Request prefix", zh: "请求前缀" },
  root: { en: "Root", zh: "根节点" },
  gpu: { en: "GPU HBM", zh: "GPU HBM" },
  host: { en: "CPU DRAM", zh: "CPU DRAM" },
  storage: { en: "External storage", zh: "外部存储" },
  query: { en: "Storage key", zh: "存储查询键" },
  local: { en: "Local prefix match", zh: "本地前缀匹配" },
  lookup: { en: "Storage lookup", zh: "查询外部存储" },
  prefetch: { en: "Storage → CPU", zh: "存储 → CPU" },
  load: { en: "CPU → GPU", zh: "CPU → GPU" },
  ready: { en: "KV ready on GPU", zh: "GPU KV 就绪" },
  absent: { en: "No local node", zh: "无本地节点" },
  layoutTitle: { en: "KV memory layout", zh: "KV 内存布局" },
  layoutNote: { en: "3 layers × 3 pages; each cell holds one layer of a page's KV.", zh: "3 层 × 3 页；每格为一页在某一层的 KV。" },
  page: { en: "Page", zh: "页" },
  layer: { en: "Layer", zh: "层" },
  layerFirst: { en: "GPU · layer-first", zh: "GPU · layer-first" },
  pageFirst: { en: "Host · page-first", zh: "Host · page-first" },
  regions: { en: "Highlighted contiguous regions", zh: "高亮的连续区域" },
  overlapTitle: { en: "Layer-wise loading", zh: "逐层加载" },
  overlapNote: { en: "Illustration: transfer = 1 unit/layer; compute = 2 units/layer. Not measured latency.", zh: "示意：每层传输 1 单位、计算 2 单位；非实测延迟。" },
  serial: { en: "Load all layers first", zh: "先加载全部层" },
  overlap: { en: "Overlap with compute", zh: "与计算重叠" },
  transfer: { en: "Transfer", zh: "传输" },
  compute: { en: "Compute", zh: "计算" },
  elapsed: { en: "Completion", zh: "完成时刻" },
  unit: { en: "units", zh: "单位" },
  policyTitle: { en: "Storage prefetch", zh: "存储预取" },
  policyNote: { en: "Toy model: one indivisible prefix; scheduling at 4, recompute = 6, warm execution = 2 units (including CPU–GPU loading).", zh: "示意：一段不可拆前缀；调度时刻 4、重算 6、命中后执行 2 单位（含 CPU–GPU 加载）。" },
  delay: { en: "Storage completion time", zh: "存储读取完成时刻" },
  best: { en: "Best effort", zh: "尽力预取" },
  wait: { en: "Wait for completion", zh: "等待完成" },
  fetched: { en: "Prefetched", zh: "预取完成" },
  cancelled: { en: "Stopped at scheduling", zh: "调度时停止" },
  cached: { en: "Warm execution", zh: "命中后执行" },
  recompute: { en: "Recompute", zh: "重新计算" },
  firstToken: { en: "First token", zh: "首 token" },
  benchTitle: { en: "Long-context benchmark", zh: "长上下文基准" },
  benchNote: { en: "DeepSeek-R1 · 8 × H20-3e · LooGLE · source: September 2025 blog", zh: "DeepSeek-R1 · 8 × H20-3e · LooGLE · 来源：2025 年 9 月博客" },
  ttft: { en: "Average TTFT (s) ↓", zh: "平均 TTFT（秒）↓" },
  throughput: { en: "Input throughput (tokens/s) ↑", zh: "输入吞吐（tokens/s）↑" },
  gpuOnly: { en: "GPU only", zh: "仅 GPU" },
  l2: { en: "+ CPU L2", zh: "+ CPU L2" },
  l3: { en: "+ 3FS L3", zh: "+ 3FS L3" },
  populated: { en: "+ Prepopulated L3", zh: "+ 预先填充 L3" },
  warmNote: { en: "Prepopulated L3 is a separate cache warmup condition. Values transcribed from the original chart.", zh: "预先填充 L3 属于不同的缓存预热条件。数值转录自原图。" },
  relative: { en: "Relative to GPU only", zh: "相对仅 GPU" },
  lower: { en: "lower TTFT", zh: "TTFT 降低" },
  higher: { en: "throughput", zh: "吞吐" },
} satisfies Record<string, Localized>;
